#
CC=$DIDBS_CC
CC=$DIDBS_CC
CPPFLAGS="-I$INSTALLDIR/include"

#CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
#CXXFLAGS="$DIDBS_ARCH_CFLAGS -O1"
#LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"

CFLAGS="$DIDBS_ARCH_CFLAGS"
CXXFLAGS="$DIDBS_ARCH_CXXFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"

PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
export CC CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL
