#
CC=$DIDBS_CC
CPPFLAGS="$DIDBS_CPPFLAGS"
CFLAGS="$CPPFLAGS $DIDBS_O1_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"

SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$SHELL"
CONFIG_SHELL="$SHELL"

export CC CPPFLAGS CFLAGS LDFLAGS SHELL SHELL_PATH CONFIG_SHELL
