#
CC=$DIDBS_CC
CPPFLAGS="$DIDBS_CPPFLAGS -I$INSTALLDIR/include"
CFLAGS="$CPPFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS -L$INSTALLDIR/lib"

SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$SHELL"
CONFIG_SHELL="$SHELL"

export CC CPPFLAGS CFLAGS LDFLAGS SHELL SHELL_PATH CONFIG_SHELL
