#
CC=$DIDBS_CC
#CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
#CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O2_NOIPA_CFLAGS"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_NOIPA_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"
SHELL=$INSTALLDIR/bin/bash
SHELL_PATH=$INSTALLDIR/bin/bash
TEST_SHELL=$INSTALLDIR/bin/bash
export CC CFLAGS LDFLAGS SHELL SHELL_PATH TEST_SHELL
