#
GBSTEST_INSTALL_DIR="$INSTALLDIR/gbstest"

CC="gcc --std=c99 $DIDBS_CPPFLAGS -D_SGI_SOURCE"
CXX="g++ $DIDBS_CPPFLAGS -D_SGI_SOURCE"
CPPFLAGS="$DIDBS_CPPFLAGS -D_SGI_SOURCE"
CFLAGS="$DIDBS_ARCH_CFLAGS -D_SGI_SOURCE"
CXXFLAGS="$DIDBS_ARCH_CFLAGS -D_SGI_SOURCE"
LDFLAGS=""

#CC=$DIDBS_CC
#CXX=$DIDBS_CXX
#CPPFLAGS="$DIDBS_CPPFLAGS -D_SGI_SOURCE"
#CFLAGS="$DIDBS_ARCH_CFLAGS -D_SGI_SOURCE $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
#CXXFLAGS="$DIDBS_ARCH_CFLAGS -D_SGI_SOURCE $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
#LDFLAGS="$DIDBS_NOWARN_LDFLAGS"


PATH="$GBSTEST_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBSTEST_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"
LD_LIBRARY_PATH="$GBSTEST_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
export CC CFLAGS LDFLAGS PATH LD_LIBRARYN32_PATH LD_LIBRARY_PATH PKG_CONFIG_PATH GBSTEST_INSTALL_DIR
