#
CC=$DIDBS_CC
CFLAGS="$DIDBS_ARCH_CFLAGS -O1 -I$INSTALLDIR/include"
CXXFLAGS="$DIDBS_ARCH_CFLAGS -O1 -I$INSTALLDIR/include"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
export CC CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL
