#
GBSTEST_INSTALL_DIR="$INSTALLDIR/gbstest"
GBS8_1_INSTALL_DIR="$INSTALLDIR/gbs8_1"

CC="gcc --std=c99 $DIDBS_CPPFLAGS"
CXX="g++ $DIDBS_CPPFLAGS"
CPPFLAGS="$DIDBS_CPPFLAGS -I/usr/Motif-2.1/include -I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS"
CXXFLAGS="$DIDBS_ARCH_CFLAGS"
LDFLAGS="-L$INSTALLDIR/lib -lXpm -ljpeg -ltiff"

SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$SHELL"
SHELL_PATH="$SHELL"
PATH="$GBS8_1_INSTALL_DIR/bin:$GBSTEST_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBS8_1_INSTALL_DIR/lib:$GBSTEST_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"
LD_LIBRARY_PATH="$GBS8_1_INSTALL_DIR/lib:$GBSTEST_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PATH LD_LIBRARYN32_PATH LD_LIBRARY_PATH PKG_CONFIG_PATH GBS8_1_INSTALL_DIR GBSTEST_INSTALL_DIR
