#
GBS0_INSTALL_DIR="$INSTALLDIR/gbs0"
GBS1_INSTALL_DIR="$INSTALLDIR/gbs1"
GBS2_INSTALL_DIR="$INSTALLDIR/gbs2"
GBS3_INSTALL_DIR="$INSTALLDIR/gbs3"

CC=gcc
CXX=g++
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBS3_INSTALL_DIR/bin:$GBS2_INSTALL_DIR/bin:$GBS1_INSTALL_DIR/bin:$PATH"
MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL CONFIG_SHELL GBS0_INSTALL_DIR GBS1_INSTALL_DIR GBS2_INSTALL_DIR GSB3_INSTALL_DIR PATH MAKEINFO
