#
CC=$DIDBS_CC
CPPFLAGS="$DIDBS_CPPFLAGS -D_SGI_SOURCE"
CFLAGS="$CPPFLAGS $DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PERL="$INSTALLDIR/bin/perl"
#export CC CFLAGS LDFLAGS
export CC CPPFLAGS CFLAGS LDFLAGS SHELL CONFIG_SHELL PERL
