#
GBS4_0_INSTALL_DIR="$INSTALLDIR/gbs4_0"
CC=c99
CXX=CC
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBS4_0_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBS4_0_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"
LD_LIBRARY_PATH="$GBS4_0_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL CONFIG_SHELL PATH LD_LIBRARYN32_PATH LD_LIBRARY_PATH MAKEINFO GBS4_0_INSTALL_DIR
