#
CC=$DIDBS_CC
CXX=$DIDBS_CXX

CPPFLAGS="$DIDBS_CPPFLAGS"

CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS -L$INSTALLDIR/lib"

CXXFLAGS="$CFLAGS"

PERL="$INSTALLDIR/bin/perl"

SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$SHELL"
TEST_SHELL="$SHELL"
CONFIG_SHELL="$SHELL"

export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL SHELL SHELL_PATH TEST_SHELL CONFIG_SHELL
