#
CC=$DIDBS_CC
CPPFLAGS="-I$INSTALLDIR/include"
# Anything other than O1 causes massive memory usage (sha512.c)
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib $DIDBS_NOWARN_LDFLAGS"
SHELL=$INSTALLDIR/bin/bash
CONFIG_SHELL=$INSTALLDIR/bin/bash
export CC CPPFLAGS CFLAGS LDFLAGS SHELL CONFIG_SHELL
