#
CC=$DIDBS_CC
CPPFLAGS="-I$INSTALLDIR/include"
# Anything other than O1 causes massive memory usage (sha512.c)
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/$DIDBS_LIBDIR $DIDBS_NOWARN_LDFLAGS"
SHELL=$INSTALLDIR/bin/bash
CONFIG_SHELL=$INSTALLDIR/bin/bash
export CC CPPFLAGS CFLAGS LDFLAGS SHELL CONFIG_SHELL
if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$INSTALLDIR/lib32"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$INSTALLDIR/lib64"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi
