#
CC=$DIDBS_CC
CPPFLAGS="-I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"
SHELL=$INSTALLDIR/bin/bash
CONFIG_SHELL=$INSTALLDIR/bin/bash
export CC CPPFLAGS CFLAGS LDFLAGS SHELL CONFIG_SHELL
