#
CC=$DIDBS_CC
BIGFILES="-D_FILE_OFFSET_BITS=64"
#CFLAGS="$DIDBS_ARCH_CFLAGS -O1 -Wall $BIGFILES"
#CFLAGS="$DIDBS_ARCH_CFLAGS -O3 -OPT:Olimit=7000 -IPA -Wall $BIGFILES"
#CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_IPA_CFLAGS -Wall $BIGFILES -fPIC"
#LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_IPA_LDFLAGS"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_NOIPA_CFLAGS -Wall $BIGFILES -fPIC"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOIPA_LDFLAGS"
export CC CFLAGS LDFLAGS BIGFILES
