#
CC=$DIDBS_CC
CXX=$DIDBS_CXX
# Errors when attempting to use system libs
# So we don't include or link
# and we specify --no-system-libs
#
# CPPFLAGS="-I$INSTALLDIR/include"
#LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"
#
CFLAGS="$DIDBS_ARCH_CFLAGS -O1 -OPT:Olimit=7000"
CXXFLAGS="$DIDBS_ARCH_CXXFLAGS -O1 -OPT:Olimit=7000"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -v"

CMAKE_INCLUDE_PATH=$INSTALLDIR/include
CMAKE_LIBRARY_PATH=$INSTALLDIR/lib
#CURSES_NEED_NCURSES=TRUE

#export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS CMAKE_INCLUDE_PATH CMAKE_LIBRARY_PATH CURSES_NEED_NCURSES
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS CMAKE_INCLUDE_PATH CMAKE_LIBRARY_PATH
