#
CC=$DIDBS_CC
CPPFLAGS="-I$INSTALLDIR/include"
#CFLAGS="$DIDBS_ARCH_CFLAGS -O1 -I$INSTALLDIR/include"
#CXXFLAGS="$DIDBS_ARCH_CFLAGS -O1 -I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
CXXFLAGS="$DIDBS_ARCH_CFLAGS -O1"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"
LD_LIBRARYN32_PATH="$INSTALLDIR/lib"
export CC CPPFLAGS CFLAGS LDFLAGS LD_LIBRARYN32_PATH
