#
GBS1_INSTALL_DIR="$INSTALLDIR/gbs1"
GBSTEST_INSTALL_DIR="$INSTALLDIR/gbstest"
CC=$DIDBS_CC
CXX=$DIDBS_CXX
CPPFLAGS="$DIDBS_CPPFLAGS"
CFLAGS="$CPPFLAGS $DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
CXXFLAGS="$CPPFLAGS $DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"

PATH="$GBSTEST_INSTALL_DIR/bin:$GBS1_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBSTEST_INSTALL_DIR/lib:$GBS1_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"
LD_LIBRARY_PATH="$GBSTEST_INSTALL_DIR/lib:$GBS1_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
export CC CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PATH LD_LIBRARYN32_PATH LD_LIBRARY_PATH PKG_CONFIG_PATH
