#
CC=$DIDBS_CC
CXX=$DIDBS_CXX
CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
#CFLAGS="$DIDBS_ARCH_CFLAGS -O3 -OPT:Olimit=7000"
CXXFLAGS="$DIDBS_ARCH_CFLAGS -O1"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"
export CC CXX CFLAGS CXXFLAGS LDFLAGS
