#
CC=$DIDBS_CC
CXX=$DIDBS_CXX
CPPFLAGS="-I$INSTALLDIR/include"
#CFLAGS="$DIDBS_ARCH_CFLAGS -O2 -I$INSTALLDIR/include"
#CXXFLAGS="$DIDBS_ARCH_CFLAGS -O2 -I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_NOIPA_CFLAGS $DIDBS_NOWARN_CFLAGS"
CXXFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_NOIPA_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib $DIDBS_NOWARN_LDFLAGS"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS
