#
GBS4_0_INSTALL_DIR="$INSTALLDIR/gbs4_0"

CC="$DIDBS_CC"
CXX="$DIDBS_CXX"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS"
CXXFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$INSTALLDIR/bin/bash"
PERL="$INSTALLDIR/bin/perl"
PERL_PATH="$INSTALLDIR/bin/perl"
#MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH MAKEINFO GBS4_0_INSTALL_DIR
