#
CC=$DIDBS_CC
CPPFLAGS="-I$INSTALLDIR/include"
#CFLAGS="$DIDBS_ARCH_CFLAGS -O1 -I$INSTALLDIR/include -I$INSTALLDIR/include/nettle"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS -I$INSTALLDIR/include -I$INSTALLDIR/include/nettle $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib -lhogweed $DIDBS_NOWARN_LDFLAGS"
LD_LIBRARYN32_PATH="$INSTALLDIR/lib"
LD_LIBRARY_PATH="$INSTALLDIR/lib"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
export CC CPPFLAGS CFLAGS LDFLAGS LD_LIBRARYN32_PATH LD_LIBRARY_PATH PKG_CONFIG_PATH
