#
CC=$DIDBS_CC
CXX=$DIDBS_CXX
CPPFLAGS="-I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS -I$INSTALLDIR/include -I$INSTALLDIR/include/nettle $DIDBS_NOWARN_CFLAGS"
CXXFLAGS="$CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/$DIDBS_LIBDIR -lhogweed $DIDBS_NOWARN_LDFLAGS"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS
if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$INSTALLDIR/lib32"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$INSTALLDIR/lib64"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi
