#
CC=$DIDBS_CC
CXX=$DIDBS_CXX
CPPFLAGS="-I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
CXXFLAGS="$DIDBS_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS -L$INSTALLDIR/lib"
SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$SHELL"
CONFIG_SHELL="$SHELL"

export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL SHELL_PATH CONFIG_SHELL
