#
CC=$DIDBS_CC
CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$INSTALLDIR/bin/bash"
TEST_SHELL="$INSTALLDIR/bin/bash"
PERL="$INSTALLDIR/bin/perl"
export CC CFLAGS LDFLAGS CONFIG_SHELL SHELL SHELL_PATH TEST_SHELL PERL
