#
GBS1_INSTALL_DIR="$INSTALLDIR/gbs1"
GBS3_INSTALL_DIR="$INSTALLDIR/gbs3"
GBS4_INSTALL_DIR="$INSTALLDIR/gbs4"

CC=gcc
CXX=g++
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$INSTALLDIR/bin/bash"
PERL="$INSTALLDIR/bin/perl"
PERL_PATH="$INSTALLDIR/bin/perl"
PATH="$GBS3_INSTALL_DIR/bin:$GBS1_INSTALL_DIR/bin:$PATH"
MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH GBS4_INSTALL_DIR GBS3_INSTALL_DIR GBS1_INSTALL_DIR PATH MAKEINFO
