CPPFLAGS="-I$INSTALLDIR/include/libdicl-0.1 $DIDBS_MP_CPPFLAGS -I$INSTALLDIR/include"

CC=gcc
CXX=g++
CFLAGS="$DIDBS_ISA_SWITCH $DIDBS_GCC_OPT_SWITCH -I$INSTALLDIR/include"
#CFLAGS="$DIDBS_ISA_SWITCH -O2 -I$INSTALLDIR/include"
#CFLAGS="$DIDBS_ISA_SWITCH -g -O2 -I$INSTALLDIR/include"
#CFLAGS="$DIDBS_ISA_SWITCH -g -O0 -I$INSTALLDIR/include"
LDFLAGS="$DIDBS_ISA_SWITCH -L$INSTALLDIR/$DIDBS_LIBDIR"
LIBS="-lgen -ldicl-0.1 -llzma -lpthread"

CXXFLAGS="$CFLAGS"
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$INSTALLDIR/bin:$PATH"

export CPPFLAGS CC CXX CFLAGS CXXFLAGS LDFLAGS LIBS PERL TEST_SHELL SHELL CONFIG_SHELL PATH
if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$INSTALLDIR/lib32:$LD_LIBRARYN32_PATH"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$INSTALLDIR/lib64:$LD_LIBRARYN64_PATH"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi

RPM_HOST_TRIPLET="mips-sgi-irix6.5"
export RPM_HOST_TRIPLET
