#export WHICH_GCC_ROOT=$INSTALLDIR/gbs4_2
#export WHICH_GCC_ROOT=$INSTALLDIR/gbs8_1
export WHICH_GCC_ROOT=$INSTALLDIR/gbs9_1

export RPM_INSTALL_DIR=$INSTALLDIR/rpmtester

CPPFLAGS="-I$INSTALLDIR/include/libdicl-0.1 $DIDBS_MP_CPPFLAGS -I$RPM_INSTALL_DIR/include -I$INSTALLDIR/include"

CC=gcc
CXX=g++
CFLAGS="$DIDBS_ISA_SWITCH -I$RPM_INSTALL_DIR/include -I$INSTALLDIR/include"
LDFLAGS="$DIDBS_ISA_SWITCH -L$RPM_INSTALL_DIR/$DIDBS_LIBDIR -L$INSTALLDIR/$DIDBS_LIBDIR"
LIBS="-lgen -ldicl-0.1 -llzma -lpthread"

CXXFLAGS="$CFLAGS"
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$RPM_INSTALL_DIR/bin:$WHICH_GCC_ROOT/bin:$PATH"

export CPPFLAGS CC CXX CFLAGS CXXFLAGS LDFLAGS LIBS PERL TEST_SHELL SHELL CONFIG_SHELL PATH
if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$RPM_INSTALL_DIR/lib32:$INSTALLDIR/lib32:$WHICH_GCC_ROOT/lib32"
    PKG_CONFIG_PATH="$RPM_INSTALL_DIR/lib32/pkgconfig:$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$RPM_INSTALL_DIR/lib64:$INSTALLDIR/lib64:$WHICH_GCC_ROOT/lib64"
    PKG_CONFIG_PATH="$RPM_INSTALL_DIR/lib64:$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi
