#
GBS1_INSTALL_DIR="$INSTALLDIR/gbs1"

CC=gcc
CXX=g++
CPPFLAGS="-I$INSTALLDIR/include -I$INSTALLDIR/include/ncurses"
CFLAGS="--std=c99 -mips4 -I$INSTALLDIR/include -I$INSTALLDIR/include/ncurses -L$INSTALLDIR/lib"
CXXFLAGS="-mips4"
LDFLAGS="-L$INSTALLDIR/lib"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$INSTALLDIR/bin/bash"
PERL="$INSTALLDIR/bin/perl"
PERL_PATH="$INSTALLDIR/bin/perl"
PATH="$GBS1_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBS1_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"
LD_LIBRARY_PATH="$GBS1_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH GBS1_INSTALL_DIR LD_LIBRARYN32_PATH LD_LIBRARY_PATH PATH
