#
GBSTEST_INSTALL_DIR="$INSTALLDIR/gbstest"
GBS8_INSTALL_DIR="$INSTALLDIR/gbs8"

CC="gcc --std=c99 $DIDBS_CPPFLAGS"
CXX="g++ $DIDBS_CPPFLAGS"
CPPFLAGS="$DIDBS_CPPFLAGS"
CFLAGS="$DIDBS_ARCH_CFLAGS -O3"
CXXFLAGS="$CFLAGS"
LDFLAGS="-L$INSTALLDIR/lib"

SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$SHELL"
SHELL_PATH="$SHELL"
PATH="$GBS8_INSTALL_DIR/bin:$GBSTEST_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBS8_INSTALL_DIR/lib:$GBSTEST_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"
LD_LIBRARY_PATH="$GBS8_INSTALL_DIR/lib:$GBSTEST_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PATH LD_LIBRARYN32_PATH LD_LIBRARY_PATH PKG_CONFIG_PATH GBS8_INSTALL_DIR GBSTEST_INSTALL_DIR
