#
CC=$DIDBS_CC
BIGFILES="-D_FILE_OFFSET_BITS=64"
CFLAGS="$DIDBS_ARCH_CFLAGS -O1 -Wall $BIGFILES"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"
PATH=$INSTALLDIR/bin:$EXTRAARGS/bin:$PATH
LD_LIBRARYN32_PATH=$INSTALLDIR/lib:$EXTRAARGS/lib:$LD_LIBRARYN32_PATH
export CC CFLAGS LDFLAGS BIGFILES PATH LD_LIBRARYN32_PATH
