#
CC=$DIDBS_CC
CXX=$DIDBS_CXX
CPPFLAGS="-I/usr/Motif-2.1/include -I$INSTALLDIR/include"

#CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
#LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib -lXpm -ljpeg -ltiff"

CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O2_NOIPA_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOIPA_CFLAGS $DIDBS_NOWARN_LDFLAGS -L$INSTALLDIR/lib -lXpm -ljpeg -ltiff"

CXXFLAGS="$CFLAGS"

LD_LIBRARYN32_PATH="$INSTALLDIR/lib"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"

export CC CXX CPPFLAGS CFLAGS LDFLAGS CXXFLAGS LD_LIBRARYN32_PATH PKG_CONFIG_PATH
