#
CC=$DIDBS_CC
CPPFLAGS="$DIDBS_CPPFLAGS"
CFLAGS="$CPPFLAGS $DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"

SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$SHELL"
CONFIG_SHELL="$SHELL"

export CC CPPFLAGS CFLAGS LDFLAGS SHELL SHELL_PATH CONFIG_SHELL

if [ "$DIDBS_LIBDIRne" = "lib32ne" ] ; then
    LD_LIBRARYN32_PATH="$INSTALLDIR/lib32"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH
else
    LD_LIBRARYN64_PATH="$INSTALLDIR/lib64"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH
fi
export PKG_CONFIG_PATH
