#export WHICH_GCC_ROOT=$INSTALLDIR/gbs4_2
#export WHICH_GCC_ROOT=$INSTALLDIR/gbs8_1
export WHICH_GCC_ROOT=$INSTALLDIR/gbs9_1

export RPM_INSTALL_DIR=$INSTALLDIR/rpmtester

CPPFLAGS="-I$INSTALLDIR/include/libdicl-0.1 $DIDBS_MP_CPPFLAGS -I$RPM_INSTALL_DIR/include -I$INSTALLDIR/include"

CC=gcc
CXX=g++
CFLAGS="$DIDBS_ISA_SWITCH -I$RPM_INSTALL_DIR/include -I$INSTALLDIR/include"
LDFLAGS="$DIDBS_ISA_SWITCH -L$RPM_INSTALL_DIR/$DIDBS_LIBDIR -L$INSTALLDIR/$DIDBS_LIBDIR -ldicl-0.1"

#CC=$DIDBS_CC
#CXX=$DIDBS_CXX
#CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS -I$INSTALLDIR/include"
#LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS -L$INSTALLDIR/$DIDBS_LIBDIR"

CXXFLAGS="$CFLAGS"
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$WHICH_GCC_ROOT/bin:$PATH"

export CC CXX CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL CONFIG_SHELL PATH
if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$INSTALLDIR/lib32:$WHICH_GCC_ROOT/lib32"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$INSTALLDIR/lib64:$WHICH_GCC_ROOT/lib64"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi
