#
GBS4_1_INSTALL_DIR="$INSTALLDIR/gbs4_1"
GBS5_0_INSTALL_DIR="$INSTALLDIR/gbs5_0"

CC=gcc
CXX=g++
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBS5_0_INSTALL_DIR/bin:$GBS4_1_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBS5_0_INSTALL_DIR/lib:$GBS4_1_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"
LD_LIBRARY_PATH="$GBS5_0_INSTALL_DIR/lib:$GBS4_1_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH GBS4_1_INSTALL_DIR GBS5_0_INSTALL_DIR PATH LD_LIBRARYN32_PATH LD_LIBRARY_PATH MAKEINFO
