#
GBS4_2_INSTALL_DIR="$INSTALLDIR/gbs4_2"
GBS5_0_INSTALL_DIR="$INSTALLDIR/gbs5_0"

CC=gcc
CXX=g++
CPPFLAGS="-I$INSTALLDIR/include"
CFLAGS="$DIDBS_ISA_SWITCH $DIDBS_GCC_OPT_SWITCH -I$INSTALLDIR/include"
CXXFLAGS="$CFLAGS"
LDFLAGS="$DIDBS_ISA_SWITCH -L$INSTALLDIR/$DIDBS_LIBDIR"
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBS5_0_INSTALL_DIR/bin:$GBS4_2_INSTALL_DIR/bin:$PATH"
MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH GBS4_2_INSTALL_DIR GBS5_0_INSTALL_DIR PATH MAKEINFO
if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$GBS5_0_INSTALL_DIR/$DIDBS_LIBDIR:$GBS4_2_INSTALL_DIR/$DIDBS_LIBDIR:$INSTALLDIR/lib32"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$GBS5_0_INSTALL_DIR/$DIDBS_LIBDIR:$GBS4_2_INSTALL_DIR/$DIDBS_LIBDIR:$INSTALLDIR/lib64"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi
