#
CC=$DIDBS_CC
CXX=$DIDBS_CXX
CPPFLAGS="-I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_NOIPA_CFLAGS"
CXXFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_NOIPA_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS
