#
CC=$DIDBS_CC
CXX=$DIDBS_CXX
CPPFLAGS="-I$INSTALLDIR/include"
#CFLAGS="$DIDBS_ARCH_CFLAGS -O2 -I$INSTALLDIR/include"
#CXXFLAGS="$DIDBS_ARCH_CFLAGS -O2 -I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS -O2"
CXXFLAGS="$DIDBS_ARCH_CFLAGS -O2"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS
