#
CC=$DIDBS_CC
CXX=$DIDBS_CXX
CPPFLAGS="-I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
CXXFLAGS="DIDBS_ARCH_CXXFLAGS -O1"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"
BZIP2_INCLUDE="$INSTALLDIR/include"
BZIP2_LIBPATH="$INSTALLDIR/lib"
BJAM_CONFIG="-j $DIDBS_JOBS --layout=system"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS BZIP2_INCLUDE BZIP2_LIBPATH BJAM_CONFIG
