#
GBS4_INSTALL_DIR="$INSTALLDIR/gbs4"
GBS6_INSTALL_DIR="$INSTALLDIR/gbs6"
CC="gcc --std=c99"
CXX="g++"
CFLAGS="$DIDBS_ARCH_CFLAGS -O2"
CPPFLAGS="-D_LANGUAGE_C -I/usr/Motif-2.1/include -I$INSTALLDIR/include"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib -lXpm -ljpeg -ltiff"
PATH="$GBS4_INSTALL_DIR/bin:$PATH"
LD_LIBRARY_PATH="$GBS4_INSTALL_DIR/lib:$INSTALLDIR/lib"
LD_LIBRARYN32_PATH="$GBS4_INSTALL_DIR/lib:$INSTALLDIR/lib"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
export CC CFLAGS CPPFLAGS LDFLAGS PATH LD_LIBRARY_PATH LD_LIBRARYN32_PATH PKG_CONFIG_PATH GBS4_INSTALL_DIR GBS6_INSTALL_DIR
