# This script is only for "sourcing" from other scripts.
# So you must set the following beforehand
#BUILDDIR=$1
#INSTALLDIR=$2

CC=$DIDBS_CC
#CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
#CXXFLAGS="$DIDBS_ARCH_CXXFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O2_NOIPA_CFLAGS $DIDBS_NOWARN_CFLAGS"
CXXFLAGS="$DIDBS_ARCH_CXXFLAGS $DIDBS_O2_NOIPA_CFLAGS $DIDBS_NOWARN_CFLAGS"
#CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_NOIPA_CFLAGS $DIDBS_NOWARN_CFLAGS"
#CXXFLAGS="$DIDBS_ARCH_CXXFLAGS $DIDBS_O3_NOIPA_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS"
SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$INSTALLDIR/bin/bash"
TEST_SHELL="$INSTALLDIR/bin/bash"
PERL="$INSTALLDIR/bin/perl"
export CC CFLAGS LDFLAGS SHELL SHELL_PATH TEST_SHELL PERL
