#
GBS9_INSTALL_DIR="$INSTALLDIR/gbs9_1"

CC="gcc"
CXX="g++"
CPPFLAGS="$DIDBS_CPPFLAGS"
CFLAGS="$DIDBS_ISA_SWITCH"
LDFLAGS="$DIDBS_ISA_SWITCH"

CXXFLAGS="$CFLAGS"

SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$SHELL"
SHELL_PATH="$SHELL"
PATH="$GBS9_INSTALL_DIR/bin:$PATH"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PATH GBS9_INSTALL_DIR

if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$GBS9_INSTALL_DIR/lib32:$INSTALLDIR/lib32"
    PKG_CONFIG_PATH="$GBS9_INSTALL_DIR/lib32/pkgconfig:$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$GBS9_INSTALL_DIR/lib64:$INSTALLDIR/lib64"
    PKG_CONFIG_PATH="$GBS9_INSTALL_DIR/lib64:$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi
