#
CC="$DIDBS_CC"
CXX="$DIDBS_CXX"
CPPFLAGS="$DIDBS_CPPFLAGS -I$INSTALLDIR/include"

#CFLAGS="$DIDBS_ARCH_CFLAGS"
#LDFLAGS="-L$INSTALLDIR/lib"

CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O2_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_IPA_LDFLAGS -L$INSTALLDIR/lib"

CXXFLAGS="$CFLAGS"

LD_LIBRARYN32_PATH="$INSTALLDIR/lib"

PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"

SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$SHELL"
SHELL_PATH="$SHELL"

export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS LD_LIBRARYN32_PATH PKG_CONFIG_PATH SHELL CONFIG_SHELL SHELL_PATH
