#
CC="$DIDBS_CC"
CXX="$DIDBS_CXX"
CPPFLAGS="$DIDBS_CPPFLAGS -I$INSTALLDIR/include"

CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O2_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_IPA_LDFLAGS -Bstatic -L$INSTALLDIR/$DIDBS_LIBDIR"

CXXFLAGS="$CFLAGS"

SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$SHELL"
SHELL_PATH="$SHELL"

export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH
if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$INSTALLDIR/lib32"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$INSTALLDIR/lib64"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi
