#
CC=$DIDBS_CC
CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"
PATH=$INSTALLDIR/bin:$EXTRAARGS/bin:$PATH
LD_LIBRARYN32_PATH=$INSTALLDIR/lib:$EXTRAARGS/lib:$LD_LIBRARYN32_PATH
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
export CC CFLAGS LDFLAGS PATH LD_LIBRARYN32_PATH PKG_CONFIG_PATH
