#
CC=$DIDBS_CC
CXX=$DIDBS_CXX
CFLAGS="$DIDBS_ARCH_CFLAGS -O1 -I${INSTALLDIR}/include"
CXXFLAGS="$DIDBS_ARCH_CXXFLAGS -O1 -I${INSTALLDIR}/include"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L${INSTALLDIR}/$DIDBS_LIBDIR"
export CC CXX CFLAGS CXXFLAGS LDFLAGS
