#
GBS4_0_INSTALL_DIR="$INSTALLDIR/gbs4_0"
GBS4_1_INSTALL_DIR="$INSTALLDIR/gbs4_1"

CC=gcc
CXX=g++
CFLAGS="-mips4"
CXXFLAGS="-mips4"
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBS4_1_INSTALL_DIR/bin:$GBS4_0_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBS4_0_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"
LD_LIBRARY_PATH="$GBS4_0_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH GBS4_1_INSTALL_DIR GBS4_0_INSTALL_DIR PATH LD_LIBRARYN32_PATH LD_LIBRARY_PATH MAKEINFO
