#
CC=$DIDBS_CC
#CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
#CFLAGS="$DIDBS_ARCH_CFLAGS -O2"
#CFLAGS="$DIDBS_ARCH_CFLAGS -O3 -OPT:Olimit=7000"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_CFLAGS -D_IO_ftrylockfile -D_IO_IN_BACKUP=0x100"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"
export CC CFLAGS LDFLAGS
