#
CC=$DIDBS_CC
CFLAGS="$DIDBS_ARCH_CFLAGS -I$INSTALLDIR/include -I$INSTALLDIR/include/nettle"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"
LD_LIBRARYN32_PATH="$INSTALLDIR/lib"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
export CC CFLAGS LDFLAGS LD_LIBRARYN32_PATH PKG_CONFIG_PATH
