#
CC=$DIDBS_CC
CFLAGS="$DIDBS_ARCH_CFLAGS -I$INSTALLDIR/include -I$INSTALLDIR/include/nettle"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/$DIDBS_LIBDIR"
export CC CFLAGS LDFLAGS

if [ "$DIDBS_LIBDIRne" = "lib32ne" ] ; then
    LD_LIBRARYN32_PATH="$INSTALLDIR/lib32"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH
else
    LD_LIBRARYN64_PATH="$INSTALLDIR/lib64"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH
fi
export PKG_CONFIG_PATH
