#
CC=$DIDBS_CC
CXX=$DIDBS_CXX
CPPFLAGS="-I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS -O1 $DIDBS_NOWARN_CFLAGS"
CXXFLAGS="$DIDBS_ARCH_CFLAGS -O1 $DIDBS_NOWARN_CFLAGS"
#CFLAGS="$DIDBS_ARCH_CFLAGS -O2"
#CXXFLAGS="$DIDBS_ARCH_CFLAGS -O2"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS -L$INSTALLDIR/lib -lintl"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$INSTALLDIR/bin/bash"
PERL="$INSTALLDIR/bin/perl"
PERL_PATH="$INSTALLDIR/bin/perl"
GSB0_TOOLS_DIR="$INSTALLDIR/gbs0"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH GSB0_TOOLS_DIR
