#
GBS8_1_INSTALL_DIR="$INSTALLDIR/gbs8_1"
GBS480_0_INSTALL_DIR="$INSTALLDIR/gbs480_0"

CC=gcc
CXX=g++
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBS480_0_INSTALL_DIR/bin:$GBS8_1_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBS480_0_INSTALL_DIR/lib:$GBS8_1_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"
LD_LIBRARY_PATH="$GBS480_0_INSTALL_DIR/lib:$GBS8_1_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH GBS8_1_INSTALL_DIR GBS480_0_INSTALL_DIR PATH LD_LIBRARYN32_PATH LD_LIBRARY_PATH MAKEINFO
