#
GBS0_INSTALL_DIR="$INSTALLDIR/gbs0"
GBS1_INSTALL_DIR="$INSTALLDIR/gbs1"
GBS2_INSTALL_DIR="$INSTALLDIR/gbs2"

# Don't use

#CC=gcc
#CXX=g++
#CPPFLAGS="-I$INSTALLDIR/include"
#CFLAGS="--std=c99 -O1 -mips4"
#CXXFLAGS="-O1 -mips4"
#LDFLAGS="-L$INSTALLDIR/lib"

CC=c99
CXX=CC
CPPFLAGS="$DIDBS_CPPFLAGS -I$INSTALLDIR/include"
CFLAGS="$DIDBS_CPPFLAGS -O1 -mips4"
CXXFLAGS="DIDBS_CPPFLAGS -O1 -mips4"
LDFLAGS="-L$INSTALLDIR/lib"

PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBS1_INSTALL_DIR/bin:$GBS0_INSTALL_DIR/bin:$PATH"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL CONFIG_SHELL GBS0_INSTALL_DIR GBS1_INSTALL_DIR GBS2_INSTALL_DIR PATH
