GBS4_1_INSTALL_DIR="$INSTALLDIR/gbs4_1"

CC="$DIDBS_CC"
CXX="$DIDBS_CXX"
#CC=gcc
#CXX=g++
CPPFLAGS="$DIDBS_CPPFLAGS -I$INSTALLDIR/include -I$INSTALLDIR/include/ncurses"
# Python uses -O anyway, override here doesn't work
CFLAGS="$DIDBS_ARCH_CFLAGS -I$INSTALLDIR/include -I$INSTALLDIR/include/ncurses"
#CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O0_CFLAGS $DIDBS_NOWARN_CFLAGS"
CXXFLAGS="$CFLAGS"
#LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS -L$INSTALLDIR/lib"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -lpthread -L$INSTALLDIR/lib"
#LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib -lgcc_s"

PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
SSL="$INSTALLDIR"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"

# Only builds when binutils as/ld are on the PATH...
PATH="$GBS4_1_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBS4_1_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"

export CC CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL SSL PATH LD_LIBRARYN32_PATH PKG_CONFIG_PATH
