GBS4_2_INSTALL_DIR="$INSTALLDIR/gbs4_2"

CC="$DIDBS_CC"
CXX="$DIDBS_CXX"
CPPFLAGS="$DIDBS_CPPFLAGS -I$INSTALLDIR/include -I$INSTALLDIR/include/ncurses"
# Python uses -O anyway, override here doesn't work
CFLAGS="$DIDBS_ISA_SWITCH"
CXXFLAGS="$CFLAGS"
LDFLAGS="$DIDBS_ISA_SWITCH -lpthread -L$INSTALLDIR/$DIDBS_LIBDIR"

PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
SSL="$INSTALLDIR"
PKG_CONFIG_PATH="$INSTALLDIR/$DIDBS_LIBDIR/pkgconfig"

# Only builds when binutils as/ld are on the PATH...
PATH="$GBS4_2_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBS4_1_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"

export CC CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL SSL PATH PKG_CONFIG_PATH

if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$GBS4_2_INSTALL_DIR/$DIDBS_LIBDIR:$INSTALLDIR/lib32"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$GBS4_2_INSTALL_DIR/$DIDBS_LIBDIR:$INSTALLDIR/lib64"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi
