CC="$DIDBS_CC"
CXX="$DIDBS_CXX"
#CPPFLAGS="$DIDBS_MP_CPPFLAGS -I$INSTALLDIR/include -I$INSTALLDIR/include/ncurses"
#CFLAGS="$DIDBS_ISA_SWITCH $DIDBS_GCC_OPT_SWITCH"
CFLAGS="$DIDBS_MP_CPPFLAGS $DIDBS_ISA_SWITCH $DIDBS_GCC_OPT_SWITCH -I$INSTALLDIR/include -I$INSTALLDIR/include/ncurses -I$INSTALLDIR/include/libdicl-0.1"
LDFLAGS="$DIDBS_ISA_SWITCH -lpthread -L$INSTALLDIR/$DIDBS_LIBDIR -ldicl-0.1"
#LIBS="-ldicl-0.1"
CXXFLAGS="$CFLAGS"

PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
SSL="$INSTALLDIR"
PKG_CONFIG_PATH="$INSTALLDIR/$DIDBS_LIBDIR/pkgconfig"

export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS LIBS PERL TEST_SHELL SHELL SSL PKG_CONFIG_PATH
if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$INSTALLDIR/lib32:$LD_LIBRARYN32_PATH"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig:$PKG_CONFIG_PATH"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$INSTALLDIR/lib64:$LD_LIBRARYN64_PATH"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig:$PKG_CONFIG_PATH"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi
