#
UNZIP_CC=$DIDBS_CC
#UNZIP_CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
UNZIP_CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_NOIPA_CFLAGS -DNO_LCHMOD"
UNZIP_LDFLAGS="$DIDBS_ARCH_LDFLAGS"
export UNZIP_CC UNZIP_CFLAGS UNZIP_LDFLAGS
if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$INSTALLDIR/lib32"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$INSTALLDIR/lib64"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi
