#
UNZIP_CC=$DIDBS_CC
#UNZIP_CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
UNZIP_CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_NOIPA_CFLAGS -DNO_LCHMOD"
UNZIP_LDFLAGS="$DIDBS_ARCH_LDFLAGS"
export UNZIP_CC UNZIP_CFLAGS UNZIP_LDFLAGS
