#
CC=$DIDBS_CC
#CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
#CFLAGS="$DIDBS_ARCH_CFLAGS -O2"
# Seem to be more issues with O3
#CFLAGS="$DIDBS_ARCH_CFLAGS -O3 -OPT:Olimit=0:space=ON -IPA"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS"
export CC CFLAGS LDFLAGS
