#
CC=$DIDBS_CC
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_IPA_CFLAGS -I$INSTALLDIR/include $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_IPA_LDFLAGS -L$INSTALLDIR/lib $DIDBS_NOWARN_LDFLAGS"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
#PYTHON=nopythonplease
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PERL="$INSTALLDIR/bin/perl"
#export CC CFLAGS LDFLAGS PKG_CONFIG_PATH PYTHON SHELL CONFIG_SHELL PERL
export CC CFLAGS LDFLAGS PKG_CONFIG_PATH SHELL CONFIG_SHELL PERL
