#
CC=$DIDBS_CC
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS -I$INSTALLDIR/include"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
PYTHON=no
export CC CFLAGS LDFLAGS PKG_CONFIG_PATH PYTHON
