#
GBS1_INSTALL_DIR="$INSTALLDIR/gbs1"
GBSTEST_INSTALL_DIR="$INSTALLDIR/gbstest"
GBS8_INSTALL_DIR="$INSTALLDIR/gbs8"

CC=gcc
CXX=g++
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBSTEST_INSTALL_DIR/bin:$GBS1_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBSTEST_INSTALL_DIR/lib:$GBS1_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"
LD_LIBRARY_PATH="$GBSTEST_INSTALL_DIR/lib:$GBS1_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH GBSTEST_INSTALL_DIR GBS1_INSTALL_DIR GBS8_INSTALL_DIR PATH LD_LIBRARYN32_PATH LD_LIBRARY_PATH MAKEINFO
