#GBS4_1_INSTALL_DIR="$INSTALLDIR/gbs4_1"
#GBS8_1_INSTALL_DIR="$INSTALLDIR/gbs8_1"

#
CC=$DIDBS_CC
CXX=$DIDBS_CXX
CPPFLAGS="$DIDBS_CPPFLAGS -I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS -woff 1552,3201,3943,3969"
CXXFLAGS="$CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS -L$INSTALLDIR/$DIDBS_LIBDIR"

#CC=gcc
#CXX=g++
#CPPFLAGS="$DIDBS_CPPFLAGS -I$INSTALLDIR/include"
#CFLAGS="$DIDBS_ARCH_CFLAGS"
#LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"

PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"

export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL CONFIG_SHELL

if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$INSTALLDIR/lib32"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$INSTALLDIR/lib64"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi
