#
CC=gcc
CXX=g++
#CFLAGS="-g -O1"
#CPPFLAGS="-I$INSTALLDIR/include"
#CFLAGS="--std=c99 $DIDBS_ARCH_CFLAGS -O1"
#CXXFLAGS="$DIDBS_ARCH_CFLAGS -O1"
#LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib -lintl"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$INSTALLDIR/bin/bash"
PERL="$INSTALLDIR/bin/perl"
PERL_PATH="$INSTALLDIR/bin/perl"
GBS0_INSTALL_DIR="$INSTALLDIR/gbs0"
GBS1_INSTALL_DIR="$INSTALLDIR/gbs1"
#PATH="$GBS1_INSTALL_DIR/bin:$GBS0_INSTALL_DIR/bin:$PATH"
PATH="$GBS1_INSTALL_DIR/bin:$PATH"
MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH GBS0_INSTALL_DIR GBS1_INSTALL_DIR PATH MAKEINFO
