#
CC=gcc
CXX=g++
CFLAGS="-g -O1"
#CPPFLAGS="-I$INSTALLDIR/include"
#CFLAGS="--std=c99 $DIDBS_ARCH_CFLAGS -O1"
#CXXFLAGS="$DIDBS_ARCH_CFLAGS -O1"
#LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib -lintl"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
SHELL_PATH="$INSTALLDIR/bin/bash"
PERL="$INSTALLDIR/bin/perl"
PERL_PATH="$INSTALLDIR/bin/perl"
GSB0_INSTALL_DIR="$INSTALLDIR/gbs0"
GSB1_INSTALL_DIR="$INSTALLDIR/gbs1"
PATH="$GSB1_INSTALL_DIR/bin:$GSB0_INSTALL_DIR/bin:$PATH"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH GSB0_INSTALL_DIR GSB1_INSTALL_DIR PATH
