#
CC=$DIDBS_CC
CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"
LD_LIBRARYN32_PATH="$INSTALLDIR/lib"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
XPM_CFLAGS="-I/usr/include/X11"
XPM_LIBS="-lX11"
export CC CFLAGS LDFLAGS LD_LIBRARYN32_PATH PKG_CONFIG_PATH XPM_CFLAGS XPM_LIBS
