#
GBS0_INSTALL_DIR="$INSTALLDIR/gbs0"
GBS1_INSTALL_DIR="$INSTALLDIR/gbs1"

# Don't use

CC=$DIDBS_CC
CXX=$DIDBS_CXX
CPPFLAGS="-I$INSTALLDIR/include"
CFLAGS="-O1 -mips4"
CXXFLAGS="-O1 -mips4"
LDFLAGS="-L$INSTALLDIR/lib"
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBS0_INSTALL_DIR/bin:$PATH"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL CONFIG_SHELL GBS0_INSTALL_DIR GBS1_INSTALL_DIR PATH
