#
GBS4_INSTALL_DIR="$INSTALLDIR/gbs4"
GBS6_INSTALL_DIR="$INSTALLDIR/gbs6"

CC=gcc
CXX=g++
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBS6_INSTALL_DIR/bin:$GBS4_INSTALL_DIR/bin:$PATH"
LD_LIBRARY_PATH="$GBS6_INSTALL_DIR/lib:$GBS4_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
LD_LIBRARYN32_PATH="$GBS6_INSTALL_DIR/lib:$GBS4_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"
MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL CONFIG_SHELL GBS4_INSTALL_DIR GBS6_INSTALL_DIR PATH MAKEINFO
