#
GBS4_1_INSTALL_DIR="$INSTALLDIR/gbs4_1"
GBS8_0_INSTALL_DIR="$INSTALLDIR/gbs8_0"

CC=gcc
CXX=g++
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBS8_0_INSTALL_DIR/bin:$GBS4_1_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBS8_0_INSTALL_DIR/lib:$GBS4_1_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"
LD_LIBRARY_PATH="$GBS8_0_INSTALL_DIR/lib:$GBS4_1_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
MAKEINFO=missing
STAGE1_CFLAGS="-O2"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH GBS4_1_INSTALL_DIR GBS8_0_INSTALL_DIR PATH LD_LIBRARYN32_PATH LD_LIBRARY_PATH MAKEINFO STAGE1_CFLAGS
