#
GBS3_INSTALL_DIR="$INSTALLDIR/gbs3"
GBS4_INSTALL_DIR="$INSTALLDIR/gbs4"

CC=gcc
CXX=g++
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBS4_INSTALL_DIR/bin:$GBS3_INSTALL_DIR/bin:$PATH"
MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL CONFIG_SHELL GBS3_INSTALL_DIR GBS4_INSTALL_DIR PATH MAKEINFO
