#
GBS9_0_INSTALL_DIR="/usr/didbs/current/gbs9_1"
GBS9_1_INSTALL_DIR="$INSTALLDIR/gbs9_1"

CC="gcc"
CXX="g++"
# For didbs 0.1.3 release
#CFLAGS="$DIDBS_ISA_SWITCH -O2"
CFLAGS="$DIDBS_ISA_SWITCH"
CXXFLAGS="$CFLAGS"
LDFLAGS="$DIDBS_ISA_SWITCH"
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"
PATH="$GBS9_1_INSTALL_DIR/bin:$GBS9_0_INSTALL_DIR/bin:$PATH"
MAKEINFO=missing
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH PERL PERL_PATH GBS9_1_INSTALL_DIR GBS9_0_INSTALL_DIR PATH MAKEINFO
if [ "ne$DIDBS_LIBDIR" == "nelib32" ]; then
    LD_LIBRARYN32_PATH="$GBS9_1_INSTALL_DIR/$DIDBS_LIBDIR:$GBS9_0_INSTALL_DIR/$DIDBS_LIBDIR:$INSTALLDIR/lib32"
    PKG_CONFIG_PATH="$INSTALLDIR/lib32/pkgconfig"
    export LD_LIBRARYN32_PATH PKG_CONFIG_PATH
else
    LD_LIBRARYN64_PATH="$GBS9_1_INSTALL_DIR/$DIDBS_LIBDIR:$GBS9_0_INSTALL_DIR/$DIDBS_LIBDIR:$INSTALLDIR/lib64"
    PKG_CONFIG_PATH="$INSTALLDIR/lib64/pkgconfig"
    export LD_LIBRARYN64_PATH PKG_CONFIG_PATH
fi
