#
CC=$DIDBS_CC
CPPFLAGS="-I$INSTALLDIR/include -D_SGI_MP_SOURCE"
CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
CXXFLAGS="$DIDBS_ARCH_CFLAGS -O1"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -Bstatic -L$INSTALLDIR/lib"
PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
export CC CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL
