#
CC="$DIDBS_CC"
CXX="$DIDBS_CXX"

#CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
#CFLAGS="$DIDBS_ARCH_CFLAGS -O3 -OPT:Olimit=7000"
#LDFLAGS="$DIDBS_ARCH_LDFLAGS"

CPPFLAPS="$DIDBS_ARCH_CPPFLAGS"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS"

SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$SHELL"
SHELL_PATH="$SHELL"

export CC CPPFLAGS CFLAGS LDFLAGS SHELL CONFIG_SHELL SHELL_PATH
