#
CC=$DIDBS_CC
CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"
#SHELL="$INSTALLDIR/bin/ksh"
#CONFIG_SHELL="$INSTALLDIR/bin/ksh"
#PERL="$INSTALLDIR/bin/perl"
#export CC CFLAGS LDFLAGS
PATH=$INSTALLDIR/bin:$EXTRAARGS/bin:$PATH
LD_LIBRARYN32_PATH=$INSTALLDIR/lib:$EXTRAARGS/lib:$LD_LIBRARYN32_PATH
export CC CFLAGS LDFLAGS SHELL CONFIG_SHELL PERL PATH LD_LIBRARYN32_PATH
