GBS8_0_INSTALL_DIR="$INSTALLDIR/gbs8_0"
GBS8_1_INSTALL_DIR="$INSTALLDIR/gbs8_1"

CC=gcc
CXX=g++
CPPFLAGS="$DIDBS_CPPFLAGS -I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS -L$INSTALLDIR/lib"

PERL="$INSTALLDIR/bin/perl"
TEST_SHELL="$INSTALLDIR/bin/bash"
SHELL="$INSTALLDIR/bin/bash"
CONFIG_SHELL="$INSTALLDIR/bin/bash"

PATH="$GBS8_0_INSTALL_DIR/bin:$PATH"
LD_LIBRARYN32_PATH="$GBS8_0_INSTALL_DIR/lib:$LD_LIBRARYN32_PATH"

export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS PERL TEST_SHELL SHELL CONFIG_SHELL PATH GBS8_1_INSTALL_DIR GBS8_0_INSTALL_DIR LD_LIBRARYN32_PATH
