#
CC="$DIDBS_CC"
CXX="$DIDBS_CXX"
CPPFLAGS="$DIDBS_CPPFLAGS -D_SGI_SOURCE -I$INSTALLDIR/include"
CFLAGS="$DIDBS_ARCH_CFLAGS -D_SGI_SOURCE"
CXXFLAGS="$DIDBS_ARCH_CFLAGS -D_SGI_SOURCE"
LDFLAGS="-L$INSTALLDIR/lib"
CC=$DIDBS_CC
CPPFLAGS="$DIDBS_CPPFLAGS -D_SGI_SOURCE"
CFLAGS="$CPPFLAGS $DIDBS_ARCH_CFLAGS $DIDBS_O1_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS"
LD_LIBRARYN32_PATH="$INSTALLDIR/lib"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
export CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS LD_LIBRARYN32_PATH PKG_CONFIG_PATH
