#
CC=$DIDBS_CC
# For debugging
#CFLAGS="$DIDBS_ARCH_CFLAGS -g -O0 -DDEBUG=1"
#DEBUG=1
#export DEBUG
#CFLAGS="$DIDBS_ARCH_CFLAGS -O1"
CFLAGS="$DIDBS_ARCH_CFLAGS $DIDBS_O3_CFLAGS $DIDBS_NOWARN_CFLAGS"
LDFLAGS="$DIDBS_ARCH_LDFLAGS $DIDBS_NOWARN_LDFLAGS"
LD_LIBRARYN32_PATH="$INSTALLDIR/lib"
PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig"
export CC CFLAGS LDFLAGS LD_LIBRARYN32_PATH PKG_CONFIG_PATH
